/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class org_swdc_recorder_core_platform_Devices */

#ifndef _Included_org_swdc_recorder_core_platform_Devices
#define _Included_org_swdc_recorder_core_platform_Devices
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_swdc_recorder_core_platform_Devices
 * Method:    getAudioDevices
 * Signature: ()Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_org_swdc_recorder_core_platform_Devices_getAudioDevices
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
